# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 11:25
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contentpage', '0002_contentpage_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
