# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 10:36
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('contentpage', '0003_auto_20171018_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.core.blocks.BlockQuoteBlock()), ('historical_event', wagtail.core.blocks.StructBlock([(b'year', wagtail.core.blocks.CharBlock()), (b'desc', wagtail.core.blocks.RichTextBlock())]))]),
        ),
    ]
