# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-13 23:46
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('contentpage', '0004_auto_20171101_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('quote', wagtail.wagtailcore.blocks.BlockQuoteBlock()), ('historical_event', wagtail.wagtailcore.blocks.StructBlock((('year', wagtail.wagtailcore.blocks.CharBlock()), ('desc', wagtail.wagtailcore.blocks.RichTextBlock())))))),
        ),
    ]
