# Generated by Django 2.0.8 on 2018-09-24 10:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('contentpage', '0006_auto_20180919_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title', icon='title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.core.blocks.BlockQuoteBlock()), ('historical_event', wagtail.core.blocks.StructBlock([('year', wagtail.core.blocks.CharBlock()), ('desc', wagtail.core.blocks.RichTextBlock())])), ('portfolio_item', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.CharBlock()), ('contrib', wagtail.core.blocks.CharBlock(blank=True)), ('link', wagtail.core.blocks.CharBlock(blank=True))]))]),
        ),
    ]
