# Generated by Django 2.0.8 on 2018-10-08 09:54

import contentpage.models
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('contentpage', '0007_auto_20180924_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title', icon='title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.core.blocks.BlockQuoteBlock()), ('historical_event', wagtail.core.blocks.StructBlock([('year', wagtail.core.blocks.CharBlock()), ('desc', wagtail.core.blocks.RichTextBlock())])), ('portfolio_item', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.CharBlock()), ('contrib', wagtail.core.blocks.CharBlock(required=False)), ('link', wagtail.core.blocks.CharBlock(required=False))])), ('divider', contentpage.models.Divider())]),
        ),
    ]
