# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 10:48
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170918_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='bodyContent',
            field=wagtail.wagtailcore.fields.StreamField([('quote', wagtail.wagtailcore.blocks.BlockQuoteBlock(max_length=225, required=True))], default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
