# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 10:51
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170918_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='bodyContent',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('quote', wagtail.core.blocks.BlockQuoteBlock(max_length=225, required=True))], default=''),
        ),
    ]
