# Generated by Django 2.0.8 on 2018-09-19 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20180919_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='intro',
            new_name='body',
        ),
    ]
